### ISSUE TITLE
Kindle version

### ISSUE THREAD

**Issue by egor-miasnikov** [awsdocs/aws-iot-greengrass-v2-developer-guide#26]
Hey team! 

Any plans to convert docs in kindle format?

Thanks

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
