### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by soumya-github** [awsdocs/aws-iot-greengrass-v2-developer-guide#27]
Whenever I deploy a component like Stream manager my GG core device deploys all other components which are already in the core there but I have not added them in deployment list. This makes deployment fail sometimes or take a long time. Is this normal and accepted. Other components running are secretsmanager,iotsitwisepublisher/processor

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
